### ISSUE TITLE
LICENSE file not found

### ISSUE THREAD

**Issue by amirouche** [Kraks/SAT.rkt#1]
Thanks for sharing this! It's helpful. I am trying to solve the package dependency issue for GNU Guile have a look at https://research.swtch.com/version-sat for an introduction.

Can you provide a LICENSE file to know whether I can port your code to LGPL?

**Comment by Kraks** [comment]
I never thought about SAT solver can be used in a package manager! That's so cool! 
I just added LICENSE file of GPL v3.
If you have any question or feature request, please let me know!
Thanks!

**Comment by amirouche** [comment]
Tx! I let you know what happens. I have a working prototype that does output the result but it doesn't use the same algo as SAT.rkt
